### ISSUE TITLE
"lt git get" does not always work

### ISSUE THREAD

**Issue by pascal-klesse** [lenneTech/cli#3]
Branch name: _feature/AKA-16-_

Working:
lt git get AKA-16 = works

Not Working:
lt git get => 16 => not working
lt git get => AKA-16 => not working
lt git get 16 => not working => error:
![Bildschirmfoto 2019-08-29 um 16 02 09](https://user-images.githubusercontent.com/54418919/63947026-789cbb80-ca76-11e9-91c0-439d8f0d3709.png)

**Comment by kaihaase** [comment]
The error occurred, because gluegun inputs can be converted automatically and therefore also numbers can be passed. The trim method in the helper class now automatically converts inputs to strings.
