### ISSUE TITLE
"lt server" opens the wrong menu

### ISSUE THREAD

**Issue by pascal-klesse** [lenneTech/cli#4]
"lt server" opens the main menu instead of the submenu

![Bildschirmfoto 2019-08-29 um 16 15 56](https://user-images.githubusercontent.com/54418919/63948077-5ad05600-ca78-11e9-9c31-108b9a79452f.png)

**Comment by kaihaase** [comment]
When calling the commandSelector in the server menu the parentCommand option was missing.
