### ISSUE TITLE
Typo when creating new Nestserver Module

### ISSUE THREAD

**Issue by DKoenig9** [lenneTech/cli#52]
When i create a new server module via cli i get an example-method. There is a typo: it is called "exampleMethode" --> the first part is in english, the second part is in german.

**Comment by kaihaase** [comment]
Solved by https://github.com/lenneTech/cli/commit/8d53a387ea0322e8f9423cea402683a54749e223

**Comment by kaihaase** [comment]
Solved by https://github.com/lenneTech/cli/commit/8d53a387ea0322e8f9423cea402683a54749e223
